# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^src/
    -   id: end-of-file-fixer
        exclude: ^src/
    -   id: check-yaml
        exclude: mkdocs.yml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Pin to a specific version of ruff to ensure consistent formatting
    rev: v0.4.4
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^cm1/
    -   id: ruff-format
        files: ^cm1/
